* 部署方案
  目前我们部署一台服务器需要较多的人工介入。过多的人工介入一方面会影响部署的准确
  性，另一方面也会出现重复执行同样操作的现象。为了尽可能保证准确性，并减少人工重
  复操作，我需要拥有一个较完善的部署工具。

  下面会列出当前遇到问题，同时给出一个期望效果。但由于要达到期望效果会使用很长时
  间，所以我们以期望效果为一大方向，给出初步解决方法。

  初步解决方法大致需要使用 12 天可以完成(不插入临时任务)。
   
** 当前问题

   1. 站点信息分散
   2. 缺少大部分自动部署措施
   3. Docker 镜像传输较耗时

** 期望
   为了达到部署工具的可扩展性，我们把“站点信息”、“具体措施”分离做为主要出发点，
   其中更看重“站点信息”。并做出如下期望：

   1. 站点信息集中管理。服务器的信息集中到一个类 servers.genee.cn 的服务。
   2. 将部署工具、监控工具等调整为仅包含“如何做”，取消管理服务器信息的功能。

** 初步解决方法
   主要出发点：“站点信息”、“具体措施”分离
   主要对象：新服务器部署

   1. 站点信息分散, 用时：1-2 天（仅整理现有站点信息的结构，信息量不增不减）
   2. 缺少大部分自动部署措施, 用时 10 天
   3. Docker 镜像传输较耗时, 采用第一种方法基本不耗时
   
*** 针对站点信息分散的解决办法
    在主要对象、主要出发点的前提下，将站点信息归纳到尽可能小的范围内，同时尽可能
    保证在用时较少的情况下完成归纳工作。

    1. 暂时手动将站点信息收集到
       - servers.genee.cn
       - docker-bind9
       - ansible
    2. Ansible 收集近乎所有站点信息。目前已将 lims2spec 信息全部纳入到 ansible
       中。但未对这些信息做相应处理，在完善 ansible 的过程中会充分利用这些信息。
       将备份、监控、vpn 纳入到 ansible 的管理范围
    3. 保持server.genee.cn、docker-bind9 中信息种类不变。

*** 针对缺少大部分自动部署措施的解决办法
    以上的主要出发点、主要对象已与马睿沟通。针对缺少大部分自动部署措施的解决办法
    已与马睿做了详细讨论。讨论结果可以参考：
    https://github.com/genee-tools/deploy-meeting/blob/master/README.org

*** 针对 Docker 镜像传输较耗时的解决办法
    1. 将 docker 镜像保存为独立的文件，由工程师带到现场，拷贝到服务器中即可（较
       快且容易）
    2. 考虑制作定制 Ubuntu 光盘，将必要服务放在光盘中，在安装系统过程中完成镜像
       的部署（较困难且耗时，目前暂时不考虑。由于之前留意到 ubunut 定制光盘相关
       文档故列出）
